import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const playFair = localFont({
  src: "./fonts/PlayfairDisplay-Regular.ttf",
  variable: "--font-playfair",
})

const inter = localFont({
  src: [
    { path: "./fonts/Inter_28pt-Light.ttf" },
    { path: "./fonts/Inter_28pt-Thin.ttf" },
  ],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playFair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
